# Generated by Django 4.0.1 on 2022-01-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0003_pin_date_added_pin_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='password',
        ),
    ]
