# Generated by Django 4.0.1 on 2022-02-02 14:20

from django.db import migrations, models
import django.db.models.deletion
import product_catalog_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0006_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog_app.category'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=product_catalog_app.models.filepath)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog_app.subcategory')),
            ],
        ),
    ]
