# Generated by Django 4.0.1 on 2022-02-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0012_alter_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
