# Generated by Django 4.0.1 on 2022-02-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0013_userused'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pin',
        ),
        migrations.DeleteModel(
            name='UserUsed',
        ),
    ]
