# Generated by Django 4.0.1 on 2022-02-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0014_delete_pin_delete_userused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
