# Generated by Django 4.0.1 on 2022-02-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0023_remove_product_subcategory_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
    ]
