# Generated by Django 4.0.1 on 2022-02-25 15:33

from django.db import migrations, models
import product_catalog_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0024_remove_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to=product_catalog_app.models.filepath),
        ),
    ]
