# Generated by Django 4.0.1 on 2022-03-24 17:37

from django.db import migrations, models
import product_catalog_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0025_alter_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=product_catalog_app.models.filepath)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='product_img', to='product_catalog_app.Picture'),
        ),
    ]
