# Generated by Django 4.0.1 on 2022-03-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0026_picture_product_item_number_remove_product_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='photo',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_catalog_app.picture'),
            preserve_default=False,
        ),
    ]
