# Generated by Django 4.0.1 on 2022-03-24 17:46

from django.db import migrations, models
import product_catalog_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0028_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=product_catalog_app.models.filepath),
        ),
    ]
