# Generated by Django 4.0.1 on 2022-03-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0029_alter_picture_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
