# Generated by Django 4.0.1 on 2022-03-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0032_remove_product_picture_product_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_number',
        ),
    ]
