# Generated by Django 4.0.1 on 2022-03-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0033_remove_product_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
