# Generated by Django 4.0.1 on 2022-03-24 18:35

from django.db import migrations, models
import product_catalog_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0034_product_item_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pictures',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=product_catalog_app.models.filepath),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
