# Generated by Django 4.0.1 on 2022-03-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0039_category_choices_remove_item_price_item_itemnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemNumber',
        ),
    ]
