# Generated by Django 4.0.1 on 2022-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0040_remove_item_itemnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemNumber',
            field=models.FloatField(null=True),
        ),
    ]
