# Generated by Django 4.0.1 on 2022-03-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0045_remove_order_item_remove_order_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
