# Generated by Django 4.0.1 on 2022-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog_app', '0046_remove_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemNumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
